# Generated by Django 6.0.6 on 2026-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amazon_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_url',
            new_name='amazon_product_url',
        ),
        migrations.AddField(
            model_name='product',
            name='noon_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='noon_product_url',
            field=models.URLField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
